//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsrOrderApp.DAL.Providers.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public Supplier()
        {
            this.SupplierToProducts = new HashSet<SupplierToProduct>();
        }
    
        public int SupplierId { get; set; }
        public string AccountNumber { get; set; }
        public short CreditRating { get; set; }
        public bool PreferredSupplierFlag { get; set; }
        public bool ActiveFlag { get; set; }
        public string PurchasingWebServiceURL { get; set; }
        public byte[] Version { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<SupplierToProduct> SupplierToProducts { get; set; }
    }
}
