//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HsrOrderApp.DAL.Providers.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierToProduct
    {
        public int SupplierToProductId { get; set; }
        public int SupplierId { get; set; }
        public int ProductId { get; set; }
        public int AverageLeadTime { get; set; }
        public decimal StandardPrice { get; set; }
        public decimal LastReceiptCost { get; set; }
        public int MinOrderQty { get; set; }
        public int MaxOrderQty { get; set; }
        public byte[] Version { get; set; }
        public Nullable<System.DateTime> LastReceiptDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Supplier Supplier { get; set; }
    }
}
